apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.fullname" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx.properties: |
    connector.name=jmx

  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4

  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4

{{ toYaml .Values.catalog | indent 2 }}
---
